### ISSUE TITLE
Allow block sizes smaller than 512

### ISSUE THREAD

**Issue by unfa** [pdesaulniers/wolf-spectrum#12]
How low an it go?

Smaller block size gives more time information, and faster scrolling.

I guess 128 or even 64 could be useful sometimes.

**Comment by pdesaulniers** [comment]
Minimum block size is 64 now. It scrolls down ridiculously fast, though. 

Related: https://github.com/pdesaulniers/wolf-spectrum/issues/16

**Comment by unfa** [comment]
Fantastic!
