### ISSUE TITLE
Draw the rulers on top of the spectrogram

### ISSUE THREAD

**Issue by unfa** [pdesaulniers/wolf-spectrum#13]
The ruler lines and captions are obsured by bright bins. Maybe it'd be good to draw that on top of the spectrograph?

Also: maybe some drop shadow could be useful for improved readability?

![image](https://user-images.githubusercontent.com/491704/45393873-45c3a280-b62e-11e8-8f93-133b179bf242.png)

**Comment by pdesaulniers** [comment]
It's basically a duplicate of https://github.com/pdesaulniers/wolf-spectrum/issues/11
