### ISSUE TITLE
Custom color ramps

### ISSUE THREAD

**Issue by unfa** [pdesaulniers/wolf-spectrum#2]
One great thing Baudline and z Sound Visualizer have is the option to change the gradient used to draw the spectrogram data.

It could be grayscale, rainbow, thermal camera style etc...

Being able to define a custom one would be great.

**Comment by pdesaulniers** [comment]
This is implemented, although it's not super fancy.
1. Copy `wolf-spectrum/plugins/wolf-spectrum/Config/Themes/default.conf` into `~/.config/wolf-spectrum.conf`
2. Tweak the values inside the config file. The colors are listed from 0dB to -90dB in steps of 10dB. You can use rgb, rgba, hsl and hsla values.
3. While the UI is running, press F12 to reload the config. Note that 

Ideally, there should be some sort of editor for configuring this.
