### ISSUE TITLE
Option to maximize the window?

### ISSUE THREAD

**Issue by unfa** [pdesaulniers/wolf-spectrum#35]
it might be nice to put Wolf Spectrum full-screen sometimes.

Right now it seems to be impossible under Plasma Desktop.

I also can't drag the window to screen edges to make it fill 1/4 or 1/2 of the screen, like I can with other windows.

Maybe it's because it's a dialog window?
Could this be changed? At least for standalone version?

**Comment by pdesaulniers** [comment]
Yes. I think it should be possible for the LV2 build as well.

**Comment by pdesaulniers** [comment]
As per commit https://github.com/pdesaulniers/wolf-spectrum/commit/6efb73f823feb042d2fe6ea026f7a937db266de2, the window should now be re-sizable like a regular window in the Jack and LV2 builds.
