### ISSUE TITLE
Hiding GUI controls

### ISSUE THREAD

**Issue by unfa** [pdesaulniers/wolf-spectrum#6]
I think being able to hide all the GUI elements and draw just the data is a useful feature - especially for creating videos about sound design, or just focusing on the data, and not control widgets.

**Comment by pdesaulniers** [comment]
I think I could just put all the GUI controls in a right-click menu.

**Comment by pdesaulniers** [comment]
I'm closing this, because I don't plan on showing any widgets, except for the captions (which can be toggled already) and a context menu for tweaking parameters.
